version: "2"
services:
  judge_server:
    image: registry.cn-qingdao.aliyuncs.com/marklux/judge-server:latest
    container_name: judge_server
    restart: always
    volumes:
      - $PWD/judge/testcases:/home/judge/testcases
      - $PWD/judge/submissions:/home/judge/submissions
      - $PWD/judge/log:/home/judge/log
      - $PWD/judge/output:/home/judge/output
    environment:
      - RPC_TOKEN={YOUR TOKEN}
      - RSYNC_HOST={YOUR RSYNC HOST}
      - RSYNC_USER={YOUR RSYNC USER}
    ports:
      - "8090:8090"